{% set name = "dtreeviz" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dtreeviz-{{ version }}.tar.gz
  sha256: b976c7f962e907c34cfa261e4346b28bcbee69db12880c249745f537a5b4be0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colour
    - python-graphviz >=0.9
    - lightgbm
    - matplotlib-base
    - numpy
    - pandas
    - pillow
    - pyspark
    - pytest
    - python >=3.6
    - scikit-learn
    - py-xgboost

test:
  imports:
    - dtreeviz
    - dtreeviz.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/parrt/dtreeviz
  summary: A Python 3 library for sci-kit learn and XGBoost decision tree visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
